spring:
    datasource:
        url: jdbc:mysql://localhost/user?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 77545211
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        driver-class-name: com.mysql.jdbc.Driver


    # redis本地环境
    redis:
        host: 127.0.0.1
        port: 6379
        password:


# swagger开关 true/false
swagger:
    enable: true


